import { Source_Code_Pro } from "next/font/google";
import "./globals.css";

const SourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});


export const metadata = {
  title: "WaitForIt.io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${SourceCodePro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
